from typing import Any

class JointModelGroup:
    def __init__(self, *args, **kwargs) -> None: ...
    def satisfies_position_bounds(self, *args, **kwargs) -> Any: ...
    @property
    def active_joint_model_bounds(self) -> Any: ...
    @property
    def active_joint_model_names(self) -> Any: ...
    @property
    def joint_model_names(self) -> Any: ...
    @property
    def name(self) -> Any: ...

class VariableBounds:
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def acceleration_bounded(self) -> Any: ...
    @property
    def jerk_bounded(self) -> Any: ...
    @property
    def max_acceleration(self) -> Any: ...
    @property
    def max_jerk(self) -> Any: ...
    @property
    def max_position(self) -> Any: ...
    @property
    def max_velocity(self) -> Any: ...
    @property
    def min_acceleration(self) -> Any: ...
    @property
    def min_jerk(self) -> Any: ...
    @property
    def min_position(self) -> Any: ...
    @property
    def min_velocity(self) -> Any: ...
    @property
    def position_bounded(self) -> Any: ...
    @property
    def velocity_bounded(self) -> Any: ...

class World:
    def __init__(self, *args, **kwargs) -> None: ...
