from typing import Any

def construct_constraints_from_node(*args, **kwargs) -> Any: ...
def construct_joint_constraint(*args, **kwargs) -> Any: ...
def construct_link_constraint(*args, **kwargs) -> Any: ...
