class MotionPlanResponse:
    def __init__(self, *args, **kwargs) -> None: ...
    def __bool__(self) -> bool: ...
    @property
    def error_code(self): ...
    @property
    def planning_time(self): ...
    @property
    def trajectory(self): ...
