from typing import Any

class MotionPlanResponse:
    def __init__(self, *args, **kwargs) -> None: ...
    def __bool__(self) -> Any: ...
    @property
    def error_code(self) -> Any: ...
    @property
    def planner_id(self) -> Any: ...
    @property
    def planning_time(self) -> Any: ...
    @property
    def start_state(self) -> Any: ...
    @property
    def trajectory(self) -> Any: ...
