class JointModelGroup:
    def __init__(self, *args, **kwargs) -> None: ...
    def satisfies_position_bounds(self, *args, **kwargs): ...
    @property
    def active_joint_model_bounds(self): ...
    @property
    def active_joint_model_names(self): ...
    @property
    def eef_name(self): ...
    @property
    def joint_model_names(self): ...
    @property
    def link_model_names(self): ...
    @property
    def name(self): ...

class RobotModel:
    def __init__(self, *args, **kwargs) -> None: ...
    def get_joint_model_group(self, *args, **kwargs): ...
    def get_model_info(self, *args, **kwargs): ...
    def has_joint_model_group(self, *args, **kwargs): ...
    @property
    def end_effectors(self): ...
    @property
    def joint_model_group_names(self): ...
    @property
    def joint_model_groups(self): ...
    @property
    def model_frame(self): ...
    @property
    def name(self): ...
    @property
    def root_joint_name(self): ...

class VariableBounds:
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def acceleration_bounded(self): ...
    @property
    def jerk_bounded(self): ...
    @property
    def max_acceleration(self): ...
    @property
    def max_jerk(self): ...
    @property
    def max_position(self): ...
    @property
    def max_velocity(self): ...
    @property
    def min_acceleration(self): ...
    @property
    def min_jerk(self): ...
    @property
    def min_position(self): ...
    @property
    def min_velocity(self): ...
    @property
    def position_bounded(self): ...
    @property
    def velocity_bounded(self): ...
