from _typeshed import Incomplete

class RobotState:
    joint_accelerations: Incomplete
    joint_efforts: Incomplete
    joint_positions: Incomplete
    joint_velocities: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def clear_attached_bodies(self, *args, **kwargs): ...
    def get_frame_transform(self, *args, **kwargs): ...
    def get_global_link_transform(self, *args, **kwargs): ...
    def get_jacobian(self, *args, **kwargs): ...
    def get_joint_group_accelerations(self, *args, **kwargs): ...
    def get_joint_group_positions(self, *args, **kwargs): ...
    def get_joint_group_velocities(self, *args, **kwargs): ...
    def get_pose(self, *args, **kwargs): ...
    def set_from_ik(self, *args, **kwargs): ...
    def set_joint_group_accelerations(self, *args, **kwargs): ...
    def set_joint_group_active_positions(self, *args, **kwargs): ...
    def set_joint_group_positions(self, *args, **kwargs): ...
    def set_joint_group_velocities(self, *args, **kwargs): ...
    def set_to_default_values(self, *args, **kwargs): ...
    def set_to_random_positions(self, *args, **kwargs): ...
    def update(self, *args, **kwargs): ...
    def __copy__(self): ...
    def __deepcopy__(self): ...
    @property
    def dirty(self): ...
    @property
    def robot_model(self): ...
    @property
    def state_info(self): ...
    @property
    def state_tree(self): ...

def robotStateToRobotStateMsg(*args, **kwargs): ...
