from typing import Any

class JointModelGroup:
    def __init__(self, *args, **kwargs) -> None: ...
    def satisfies_position_bounds(self, *args, **kwargs) -> Any: ...
    @property
    def active_joint_model_bounds(self) -> Any: ...
    @property
    def active_joint_model_names(self) -> Any: ...
    @property
    def eef_name(self) -> Any: ...
    @property
    def joint_model_names(self) -> Any: ...
    @property
    def link_model_names(self) -> Any: ...
    @property
    def name(self) -> Any: ...

class RobotModel:
    def __init__(self, *args, **kwargs) -> None: ...
    def get_joint_model_group(self, *args, **kwargs) -> Any: ...
    def get_model_info(self, *args, **kwargs) -> Any: ...
    def has_joint_model_group(self, *args, **kwargs) -> Any: ...
    @property
    def end_effectors(self) -> Any: ...
    @property
    def joint_model_group_names(self) -> Any: ...
    @property
    def joint_model_groups(self) -> Any: ...
    @property
    def model_frame(self) -> Any: ...
    @property
    def name(self) -> Any: ...
    @property
    def root_joint_name(self) -> Any: ...

class VariableBounds:
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def acceleration_bounded(self) -> Any: ...
    @property
    def jerk_bounded(self) -> Any: ...
    @property
    def max_acceleration(self) -> Any: ...
    @property
    def max_jerk(self) -> Any: ...
    @property
    def max_position(self) -> Any: ...
    @property
    def max_velocity(self) -> Any: ...
    @property
    def min_acceleration(self) -> Any: ...
    @property
    def min_jerk(self) -> Any: ...
    @property
    def min_position(self) -> Any: ...
    @property
    def min_velocity(self) -> Any: ...
    @property
    def position_bounded(self) -> Any: ...
    @property
    def velocity_bounded(self) -> Any: ...
