name: docker

on:
  schedule:
    # 5 PM UTC every Sunday
    - cron:  '0 17 * * 6'
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .docker/**
      - .github/workflows/docker.build.yaml
      - .github/workflows/docker.yaml
      - "*.repos"

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [lyrical, rolling]
    permissions:
      packages: write
      contents: read
    uses: ./.github/workflows/docker.build.yaml
    with:
      image: moveit/moveit2:${{ matrix.ROS_DISTRO }}-release
      dockerfile: .docker/release/Dockerfile
      ros_distro: ${{ matrix.ROS_DISTRO }}
      check_apt_updates: true
    secrets: inherit

  ci:
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [lyrical, rolling]
    permissions:
      packages: write
      contents: read
    uses: ./.github/workflows/docker.build.yaml
    with:
      image: moveit/moveit2:${{ matrix.ROS_DISTRO }}-ci
      dockerfile: .docker/ci/Dockerfile
      ros_distro: ${{ matrix.ROS_DISTRO }}
      check_apt_updates: true
    secrets: inherit

  ci-testing:
    needs: ci
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [lyrical, rolling]
    permissions:
      packages: write
      contents: read
    uses: ./.github/workflows/docker.build.yaml
    with:
      image: moveit/moveit2:${{ matrix.ROS_DISTRO }}-ci-testing
      dockerfile: .docker/ci-testing/Dockerfile
      ros_distro: ${{ matrix.ROS_DISTRO }}
      check_apt_updates: true
    secrets: inherit

  source:
    needs: ci-testing
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [lyrical, rolling]
    permissions:
      packages: write
      contents: read
    uses: ./.github/workflows/docker.build.yaml
    with:
      image: moveit/moveit2:${{ matrix.ROS_DISTRO }}-source
      dockerfile: .docker/source/Dockerfile
      ros_distro: ${{ matrix.ROS_DISTRO }}
      full_source_context: true
    secrets: inherit

  tutorial-source:
    needs: source
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [lyrical, rolling]
    permissions:
      packages: write
      contents: read
    uses: ./.github/workflows/docker.build.yaml
    with:
      image: moveit/moveit2:main-${{ matrix.ROS_DISTRO }}-tutorial-source
      dockerfile: .docker/tutorial-source/Dockerfile
      ros_distro: ${{ matrix.ROS_DISTRO }}
    secrets: inherit

  delete_untagged:
    runs-on: ubuntu-latest
    needs:
      - release
      - source
      - tutorial-source
    steps:
      - name: Delete Untagged Images
        if: (github.event_name != 'pull_request') && (github.repository == 'moveit/moveit2')
        uses: actions/github-script@v9
        with:
          github-token: ${{ secrets.DELETE_PACKAGES_TOKEN }}
          script: |
            const response = await github.request("GET /orgs/${{ env.OWNER }}/packages/container/${{ env.PACKAGE_NAME }}/versions", {
                per_page: ${{ env.PER_PAGE }}
              });
            for(version of response.data) {
                if (version.metadata.container.tags.length == 0) {
                    console.log("delete " + version.id)
                    const deleteResponse = await github.request("DELETE /orgs/${{ env.OWNER }}/packages/container/${{ env.PACKAGE_NAME }}/versions/" + version.id, { });
                    console.log("status " + deleteResponse.status)
                }
            }
        env:
          OWNER: moveit
          PACKAGE_NAME: moveit2
          PER_PAGE: 100
